# Generated by Django 5.2.13 on 2026-04-19 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskTriggerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        help_text="Celery task ID", max_length=255, unique=True
                    ),
                ),
                (
                    "task_name",
                    models.CharField(help_text="Task name/path", max_length=255),
                ),
                (
                    "args",
                    models.JSONField(
                        blank=True, default=list, help_text="Task arguments"
                    ),
                ),
                (
                    "kwargs",
                    models.JSONField(
                        blank=True, default=dict, help_text="Task keyword arguments"
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result",
                    models.TextField(
                        blank=True, help_text="Task result or error message", null=True
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Trigger History",
                "verbose_name_plural": "Task Trigger Histories",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
